/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Foo_CallC */

#ifndef _Included_Foo_CallC
#define _Included_Foo_CallC
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Foo_CallC
 * Method:    intMethod
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Foo_CallC_intMethod
  (JNIEnv *, jobject, jint);

/*
 * Class:     Foo_CallC
 * Method:    booleanMethod
 * Signature: (Z)Z
 */
JNIEXPORT jboolean JNICALL Java_Foo_CallC_booleanMethod
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     Foo_CallC
 * Method:    stringMethod
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Foo_CallC_stringMethod
  (JNIEnv *, jobject, jstring);

/*
 * Class:     Foo_CallC
 * Method:    intArrayMethod
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_Foo_CallC_intArrayMethod
  (JNIEnv *, jobject, jintArray);

#ifdef __cplusplus
}
#endif
#endif
